server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shiro?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 199368
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
  thymeleaf:
    cache: false



